# Generated by Django 4.2.5 on 2023-09-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='equipo',
            new_name='nombre',
        ),
    ]
