# Generated by Django 4.2.5 on 2023-09-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0002_rename_equipo_post_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Equipo',
        ),
    ]
