# Generated by Django 4.2.5 on 2023-09-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0003_rename_post_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dorsal', models.IntegerField(max_length=2)),
            ],
        ),
    ]
